import { z } from 'zod';

/**
 * Input schemas. Every input crossing the boundary is hostile until it has been
 * through one of these — parsed at the top of the handler, before anything touches
 * a query.
 *
 * NOT server-only, deliberately. A Zod schema contains no secret, and `design` can
 * reuse these to validate the checkout form in the browser. That is not a
 * duplicate source of truth: it is the *same* source of truth, evaluated twice.
 * The browser copy is a courtesy to the user; the server copy is the one that
 * decides.
 *
 * The bounds mirror the CHECK constraints in `supabase/migrations/0001_schema.sql`
 * exactly (see `supabase/CONTRACT.md`), so Zod rejects bad input with a field-level
 * message instead of letting Postgres reject it with an opaque one. The database
 * remains the last line — these are the first.
 *
 * Every message is a MACHINE KEY, not copy. The site is bilingual; `design` maps
 * these keys to `src/i18n/{ar,en}.ts`. Never render one raw.
 */

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

const emailSchema = z
  .string()
  .trim()
  .min(1, 'REQUIRED')
  .max(254, 'TOO_LONG')
  .email('INVALID_EMAIL');

export const signUpSchema = z.object({
  email: emailSchema,
  password: z
    .string()
    .min(8, 'TOO_SHORT')
    // 72 bytes is bcrypt's hard ceiling. Past it, extra characters are silently
    // ignored — two different passwords would both open the account.
    .max(72, 'TOO_LONG'),
  /**
   * Optional. `profiles.full_name` is nullable precisely because email+password
   * signup may carry no name (the user can add it later). When present it goes
   * into `raw_user_meta_data`, where the `on_auth_user_created` trigger reads it.
   */
  fullName: z.string().trim().min(2, 'TOO_SHORT').max(80, 'TOO_LONG').optional(),
});

export const signInSchema = z.object({
  email: emailSchema,
  // No min(8) here, on purpose. Applying the sign-up policy at sign-in would
  // reject the legitimate old password of anyone who registered before the policy
  // — and tell them it was "too short". Sign-in checks a password, it does not
  // grade it.
  password: z.string().min(1, 'REQUIRED'),
});

// ---------------------------------------------------------------------------
// Orders
// ---------------------------------------------------------------------------

/**
 * The maximum quantity of any one product in an order.
 *
 * This is 20 because `order_items.qty` has a `CHECK (qty between 1 and 20)`
 * (CONTRACT.md §1). It is applied to the MERGED quantity per product — the RPC
 * sums duplicate cart lines before it checks.
 *
 * `design`: import this constant for the cart's `+` button cap. Do not retype the
 * number. If the UI caps at a different value than the database, the user gets a
 * validation error on an action the interface told them was allowed.
 */
export const MAX_QTY_PER_PRODUCT = 20;

/** Hard cap on distinct lines in one order. Six products exist; 20 is slack. */
export const MAX_ORDER_LINES = 20;

const orderItemSchema = z.object({
  productId: z.string().uuid('INVALID_ID'),
  qty: z
    .number()
    .int('NOT_AN_INTEGER')
    .min(1, 'TOO_LOW')
    .max(MAX_QTY_PER_PRODUCT, 'TOO_HIGH'),
});

export const placeOrderSchema = z.object({
  items: z
    .array(orderItemSchema)
    .min(1, 'EMPTY_CART')
    // An unbounded array is free work for a hostile caller.
    .max(MAX_ORDER_LINES, 'TOO_MANY_ITEMS')
    .refine((items) => new Set(items.map((i) => i.productId)).size === items.length, {
      message: 'DUPLICATE_PRODUCT',
    }),

  /** ASK for the discount. Do not compute it. Postgres decides, under a row lock. */
  redeemReward: z.boolean(),

  // orders.customer_* CHECKs: name 1..80, phone 5..32, address 1..300.
  customerName: z.string().trim().min(1, 'REQUIRED').max(80, 'TOO_LONG'),
  customerPhone: z
    .string()
    .trim()
    .min(5, 'TOO_SHORT')
    .max(32, 'TOO_LONG')
    .regex(/^[0-9+()\-\s]+$/, 'INVALID_PHONE'),
  customerAddress: z.string().trim().min(1, 'REQUIRED').max(300, 'TOO_LONG'),

  /**
   * Idempotency key. ONE uuid per checkout attempt, generated by the client with
   * `crypto.randomUUID()` and REUSED across every retry of that attempt.
   *
   * Required, not optional. `place_order` accepts null and simply switches
   * idempotency off — at which point a double-clicked Confirm quietly creates two
   * pending orders. Making it mandatory here deletes that footgun: you cannot
   * forget to pass it, because it will not parse.
   *
   * It cannot be generated server-side. A retry would get a fresh token and place
   * a second order, which is the exact thing it exists to prevent.
   */
  clientToken: z.string().uuid('INVALID_ID'),
});

export const orderIdSchema = z.object({
  orderId: z.string().uuid('INVALID_ID'),
});

// ---------------------------------------------------------------------------
// Inferred input types — the parameter types of the server actions.
// ---------------------------------------------------------------------------

export type SignUpInput = z.infer<typeof signUpSchema>;
export type SignInInput = z.infer<typeof signInSchema>;
export type PlaceOrderInput = z.infer<typeof placeOrderSchema>;
export type OrderIdInput = z.infer<typeof orderIdSchema>;

/**
 * Note what no schema on this page accepts: a price, a unit price, a subtotal, a
 * discount, a total, or a userId.
 *
 * A client-supplied price cannot reach a query — nothing parses one, and the RPC
 * has no parameter that would take one. The subtotal is recomputed in Postgres from
 * `products` on every call. Identity comes from the verified session cookie via
 * `auth.uid()`, never from the request body.
 */
